spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: notification
  redis:
    host: redis
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: 21110778@student.hcmute.edu.vn
    password: phamkimngan
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@discovery:8761/eureka

---

apartment:
  notification:
    email:
      from: 21110778@student.hcmute.edu.vn
      bcc: ams.hcmute@gmail.com
      max-retry-times: 3