eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@discovery:8761/eureka
---

apartment:
  master:
    url: http://master:8083

---

paypal:
  success:
    url: http://localhost:8084